# Nombre de la aplicacion
spring.application.name=${NombreAplicacion:IA}
server.port=${PuertoServidor:8080}

# Propiedades para el tamanno de las imagenes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# REMEMBER ME CONFIGURATION
security.rememberme.key=${REMEMBER_ME_KEY}
security.rememberme.token-validity=${REMEMBER_ME_TOKEN}

# Ajustes del JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

# Configuracion de la base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configuracion del pool de conexiones HikariCP
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

# Configuracion de IA
spring.ai.model.chat=ollama
spring.ai.ollama.base-url=${OPENAI_BASE_URL}
spring.ai.ollama.chat.options.model=${OPENAI_MODEL:gemma3:latest}
spring.ai.ollama.chat.options.temperature=0.2
app.ai.negacion-respuesta = ${NEGATIVEANSWERS_APP_AI}

## Activar memoria con JDBC
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

# OAuth2 Client Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.provider.google.user-name-attribute=email

# Errores personalizados
server.servlet.session.tracking-modes=cookie
spring.web.error.whitelabel.enabled=false
spring.web.error.path=/error
spring.web.error.include-message=always